name: 2thecore

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: 2thecore-rabbitmq
    ports:
      - "5672:5672"       # AMQP
      - "15672:15672"     # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: 2thecore
      RABBITMQ_DEFAULT_PASS: 2thecore
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    container_name: 2thecore-redis
    ports:
      - "6379:6379"
    networks:
      - rabbitmq_net
    restart: unless-stopped


volumes:
  rabbitmq_data:

networks:
  rabbitmq_net:
