spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example._thecore_back.car
  configuration:
    map-underscore-to-camel-case: true

  jpa:
    hibernate:
      ddl-auto: create       # 테이블 자동 생성
    show-sql: true           # SQL 콘솔에 출력
    properties:
      hibernate:
        format_sql: true     # SQL 예쁘게 출력
    defer-datasource-initialization: true
