server:
  port: ${HUB_SERVER_PORT}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.web: DEBUG

car:
  reader:
    db:
      enabled: ${CAR_DB_ENABLED:false}

emulator:
  reader:
    db:
      enabled: ${EMULATOR_DB_ENABLED:false}

jwt:
  secret: ${JWT_SECRET_KEY}
#
#server:
#  port: 8082
#
#spring:
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: 2thecore
#    password: 2thecore
#  data:
#    redis:
#      host: localhost
#      port: 6379
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#
#car:
#  reader:
#    db:
#      enabled: false

#emulator:
#  reader:
#    db:
#      enabled: false
#
#jwt:
#  secret: my_secret_key_for_hmac_sha256_algorithm_256bit