server:
  port: 8082

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: 2thecore
    password: 2thecore
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org.springframework.web: DEBUG

car:
  reader:
    db:
      enabled: false

emulator:
  reader:
    db:
      enabled: false

jwt:
  secret: my_secret_key_for_hmac_sha256_algorithm_256bit
